### ISSUE TITLE
Headers are overwritten when pinDns is enabled

### ISSUE THREAD

**Issue by jmyns** [j0k3r/safecurl#7]
Use case: Many times custom headers are required for authentication purposes.  SafeCurl should not overwrite headers.

Steps to Reproduce:

```
$curlHandle = curl_init();
			
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                    'CustomHeader1: 0',
                    'CustomHeader2: auth'
                ));
			
$options = new Options();
$options->disblePinDns();
			
$response = $safeCurl->execute($url, $options);
```

Expected Result:
CustomHeader1 and CustomHeader2 are sent in the request

Actual Result:
Custom headers are overwritten here:
curl_setopt($curlHandle, CURLOPT_HTTPHEADER, array('Host: ' . $url));

**Comment by j0k3r** [comment]
Sadly there is no proper way to retrieve the pre-defined http header when using curl directly.
https://stackoverflow.com/a/5356201/569101

We should rewrote it completely with a custom wrapper (which won't happen).
